os: windows

language: python
python:
  - "3.10"

install:
  - pip install -U pyinstaller


script:
  - pyinstaller --onefile --console main.py


before_deploy:
  # Set up git user name and tag this commit
  - git config --local user.name "Ishaaq"
  - git config --local user.email "admin@eshark.tk"
  - export TRAVIS_TAG=${TRAVIS_TAG:-$(date +'%Y%m%d%H%M%S')-$(git log --format=%h -1)}
  - git tag $TRAVIS_TAG

deploy:
  provider: releases
  api_key:
    secure: xTlSo0AWLhTD7fDMDb6s+KH1M3xUmCIJ4WMr/iPXc475iMrFRljPDLRutGCJ6AW2mds9XRcWF7ITMO5IzvgnFn65Jw9xapvnv8MGDQEK2tQ3ywxypV8RNHvdh+4M/2jtSHGTyfZluEfTPJxwY8VkErdTfcDje0ZsZpfJj/Pb/3aEWya8vGXwVvtwhUnAd/syGgdzTWzMPk4P+UwTlUq4wwWtc5yCGGK6e44tHhjGoVYOLiaSBkbc2Rs0Q1F1CIIVbRSYLz9UN65o8GUcukzRPHWkxIY7i5fhvMjTapj8UHx8ZC8VTXB2KCXtL3nshr4WOms0GFKoSa4pH3Zg8iMQ6V/tm9V4AKH00QCZ1ntc5fY2yP/4YefCVdgPJza4bjdewLUWzIwvBHkz2dHARY0isY6v7XXs3BHuB5XEL+gRBKDkOevEEIdHrTcKjhmfpVss3UeQm/SrT+gH98I6og2Oj+o0zuHJn63qoUoHJF48ixR3F/ASnvnNtTzGOeSmo5BTuxsg6Ju3yVVetfOX4opR1DCE5wdXMIARiRobDn+4qN609tFEU4Kfc++c0WRNjk9KP4BUCk+w9MMeQVRDCrLDbH269HtqH6BA+SjotC5gPeYZnHWU5TvZHb/go/8jMWhbKsuGmS8at5Y8SzVt220UF8/F88O+ZBwHDqJ58Qca2EQ=
  file: "/dist/main.exe"
  skip_cleanup: 'true'